# Generated by Django 4.2.6 on 2023-10-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi_berita', models.TextField()),
                ('jenis_berita', models.CharField(max_length=100)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('ditulis_oleh', models.CharField(max_length=255)),
                ('banner_berita', models.ImageField(upload_to='berita_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('nama_pengguna', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(null=True, upload_to='blog_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
                ('penulis', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('buku_pdf', models.FileField(upload_to='buku_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='CeritaPendek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi_cerita', models.TextField()),
                ('pengguna', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'profile_picture'],
            },
        ),
    ]
