# Generated by Django 5.0.4 on 2024-06-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='buku_pdf',
        ),
        migrations.AddField(
            model_name='buku',
            name='buku_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
