# Generated by Django 4.2.6 on 2023-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
