# Generated by Django 4.2.6 on 2023-10-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi_berita', models.TextField()),
                ('jenis_berita', models.CharField(max_length=100)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('ditulis_oleh', models.CharField(max_length=255)),
                ('banner_berita', models.ImageField(upload_to='berita_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('nama_pengguna', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='blog_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
                ('penulis', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('buku_pdf', models.FileField(upload_to='buku_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='CeritaPendek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi_cerita', models.TextField()),
                ('pengguna', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
