# Generated by Django 4.2.6 on 2023-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_nama_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='blog_banners/'),
        ),
    ]
