# Generated by Django 4.2.6 on 2023-10-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='banner',
        ),
    ]
