# Generated by Django 4.2.6 on 2023-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jurusan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AKL'), (2, 'APHP'), (3, 'TBSM'), (4, 'TJKT'), (5, 'TKRO'), (6, 'TP')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kelas',
            field=models.PositiveSmallIntegerField(choices=[(1, 'X'), (2, 'XI'), (3, 'XII')], null=True),
        ),
    ]
