# Generated by Django 4.2.6 on 2023-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nama_pengguna',
            field=models.CharField(max_length=255),
        ),
    ]
