# Generated by Django 4.2.6 on 2023-11-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_berita_jenis_berita_berita_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puisi',
            name='tema',
        ),
    ]
