# Generated by Django 4.2.6 on 2023-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_puisi_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='sampul',
            field=models.ImageField(default=1, upload_to='sampul_buku/'),
            preserve_default=False,
        ),
    ]
