# Generated by Django 4.2.6 on 2023-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blog_nama_pengguna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puisi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('penulis', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
