# Generated by Django 5.0.4 on 2024-05-18 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_comment_blog_commentblog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='liked_blogs', through='main.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
